import { Category, Deal, Store } from "./types";

/** Build a placeholder product image URL with a solid background and centered label. */
function img(label: string, bg = "FF6B00", fg = "FFFFFF"): string {
  const text = encodeURIComponent(label);
  return `https://placehold.co/600x600/${bg}/${fg}?text=${text}&font=roboto`;
}

export const categories: Category[] = [
  { slug: "electronics", name: "Electronics", icon: "🔌", description: "TVs, headphones, cameras & smart gadgets" },
  { slug: "fashion", name: "Fashion", icon: "👗", description: "Clothing, footwear & accessories" },
  { slug: "mobiles", name: "Mobiles", icon: "📱", description: "Smartphones from every top brand" },
  { slug: "laptops", name: "Laptops", icon: "💻", description: "Laptops & computer accessories" },
  { slug: "home-kitchen", name: "Home & Kitchen", icon: "🏠", description: "Appliances & everyday essentials" },
  { slug: "travel", name: "Travel", icon: "✈️", description: "Flights, hotels & holiday packages" },
  { slug: "beauty", name: "Beauty", icon: "💄", description: "Skincare, makeup & personal care" },
  { slug: "food", name: "Food", icon: "🍔", description: "Food delivery & dining offers" },
  { slug: "gaming", name: "Gaming", icon: "🎮", description: "Consoles, games & accessories" },
  { slug: "subscriptions", name: "Subscriptions", icon: "🎬", description: "Streaming, music & OTT plans" },
];

export const stores: Store[] = [
  { slug: "amazon", name: "Amazon", color: "232F3E", description: "Everything store with daily deals across every category." },
  { slug: "flipkart", name: "Flipkart", color: "2874F0", description: "India's homegrown marketplace for electronics & fashion." },
  { slug: "myntra", name: "Myntra", color: "FF3F6C", description: "Fashion and lifestyle destination for trending styles." },
  { slug: "ajio", name: "Ajio", color: "2A2A72", description: "Curated fashion from national and international brands." },
  { slug: "croma", name: "Croma", color: "00A19C", description: "Electronics superstore for gadgets and appliances." },
  { slug: "reliance-digital", name: "Reliance Digital", color: "E4002B", description: "One-stop shop for electronics and home appliances." },
  { slug: "nykaa", name: "Nykaa", color: "FC2779", description: "Beauty and wellness products from top brands." },
  { slug: "firstcry", name: "FirstCry", color: "6EC531", description: "Everything for babies, kids & parents." },
  { slug: "tata-cliq", name: "Tata CLiQ", color: "E31E24", description: "Premium fashion and electronics marketplace." },
  { slug: "apple", name: "Apple", color: "111111", description: "iPhones, MacBooks, iPads and accessories." },
  { slug: "samsung", name: "Samsung", color: "1428A0", description: "Galaxy phones, TVs and smart home devices." },
  { slug: "boat", name: "boAt", color: "E30613", description: "Audio gear and wearables for everyday life." },
  { slug: "nike", name: "Nike", color: "111111", description: "Footwear and sportswear for every athlete." },
  { slug: "adidas", name: "Adidas", color: "000000", description: "Sportswear, sneakers and performance gear." },
];

export const deals: Deal[] = [
  {
    id: "1",
    slug: "apple-airpods-pro-2",
    title: "Apple AirPods Pro (2nd Gen)",
    description: "Active noise cancellation, adaptive audio and up to 6 hours of listening time on a single charge.",
    categorySlug: "electronics",
    storeSlug: "amazon",
    image: img("AirPods Pro"),
    originalPrice: 24900,
    discountedPrice: 19999,
    coupon: "SAVE20",
    expiry: "2026-08-15",
    popularity: 96,
    dateAdded: "2026-07-27",
    featured: true,
  },
  {
    id: "2",
    slug: "samsung-galaxy-s25-ultra",
    title: "Samsung Galaxy S25 Ultra 256GB",
    description: "Flagship Galaxy with a 200MP camera, titanium frame and Galaxy AI built in.",
    categorySlug: "mobiles",
    storeSlug: "samsung",
    image: img("Galaxy S25 Ultra", "1428A0"),
    originalPrice: 129999,
    discountedPrice: 104999,
    coupon: "GALAXY19",
    expiry: "2026-08-10",
    popularity: 94,
    dateAdded: "2026-07-28",
    featured: true,
  },
  {
    id: "3",
    slug: "macbook-air-m3",
    title: "Apple MacBook Air 13\" M3",
    description: "8-core CPU, all-day battery life and a stunning Liquid Retina display.",
    categorySlug: "laptops",
    storeSlug: "apple",
    image: img("MacBook Air M3", "111111"),
    originalPrice: 114900,
    discountedPrice: 99900,
    coupon: "AIRM3",
    expiry: "2026-08-05",
    popularity: 91,
    dateAdded: "2026-07-25",
    featured: true,
  },
  {
    id: "4",
    slug: "nike-air-max-270",
    title: "Nike Air Max 270 Sneakers",
    description: "Nike's biggest heel Air unit yet for all-day comfort and street-ready style.",
    categorySlug: "fashion",
    storeSlug: "nike",
    image: img("Air Max 270", "111111"),
    originalPrice: 12995,
    discountedPrice: 7797,
    coupon: "AIRMAX40",
    expiry: "2026-08-20",
    popularity: 82,
    dateAdded: "2026-07-24",
  },
  {
    id: "5",
    slug: "boat-rockerz-450-pro",
    title: "boAt Rockerz 450 Pro Headphones",
    description: "40mm drivers, up to 70 hours of playback and quick charge support.",
    categorySlug: "electronics",
    storeSlug: "boat",
    image: img("Rockerz 450", "E30613"),
    originalPrice: 2999,
    discountedPrice: 1499,
    coupon: "BOAT50",
    expiry: "2026-08-12",
    popularity: 88,
    dateAdded: "2026-07-26",
  },
  {
    id: "6",
    slug: "adidas-ultraboost-22",
    title: "Adidas Ultraboost 22 Running Shoes",
    description: "Responsive Boost midsole engineered for energy return on every run.",
    categorySlug: "fashion",
    storeSlug: "adidas",
    image: img("Ultraboost 22", "000000"),
    originalPrice: 17999,
    discountedPrice: 10799,
    coupon: "RUN40",
    expiry: "2026-08-18",
    popularity: 76,
    dateAdded: "2026-07-20",
  },
  {
    id: "7",
    slug: "dell-xps-13-plus",
    title: "Dell XPS 13 Plus Laptop",
    description: "13th Gen Intel Core, InfinityEdge display and a zero-lattice keyboard.",
    categorySlug: "laptops",
    storeSlug: "croma",
    image: img("Dell XPS 13", "00A19C"),
    originalPrice: 139990,
    discountedPrice: 112990,
    coupon: "DELL19",
    expiry: "2026-08-08",
    popularity: 79,
    dateAdded: "2026-07-22",
  },
  {
    id: "8",
    slug: "oneplus-12r-5g",
    title: "OnePlus 12R 5G (256GB)",
    description: "Snapdragon 8 Gen 2, 100W SUPERVOOC charging and a 120Hz ProXDR display.",
    categorySlug: "mobiles",
    storeSlug: "flipkart",
    image: img("OnePlus 12R", "2874F0"),
    originalPrice: 45999,
    discountedPrice: 37999,
    coupon: "PLUS15",
    expiry: "2026-08-14",
    popularity: 85,
    dateAdded: "2026-07-27",
  },
  {
    id: "9",
    slug: "nykaa-lip-kit",
    title: "Nykaa Cosmetics Matte Lip Kit",
    description: "Long-lasting matte lipstick trio in everyday wearable shades.",
    categorySlug: "beauty",
    storeSlug: "nykaa",
    image: img("Nykaa Lip Kit", "FC2779"),
    originalPrice: 1497,
    discountedPrice: 899,
    coupon: "GLAM40",
    expiry: "2026-08-25",
    popularity: 68,
    dateAdded: "2026-07-18",
  },
  {
    id: "10",
    slug: "myntra-denim-jacket",
    title: "Roadster Men's Denim Jacket",
    description: "Classic washed-denim jacket with button closure for everyday layering.",
    categorySlug: "fashion",
    storeSlug: "myntra",
    image: img("Denim Jacket", "FF3F6C"),
    originalPrice: 2999,
    discountedPrice: 1499,
    coupon: "MYNTRA50",
    expiry: "2026-08-11",
    popularity: 60,
    dateAdded: "2026-07-15",
  },
  {
    id: "11",
    slug: "lg-55-inch-4k-tv",
    title: "LG 55\" 4K UHD Smart LED TV",
    description: "WebOS smart platform, AI picture processing and Dolby Vision support.",
    categorySlug: "electronics",
    storeSlug: "reliance-digital",
    image: img("LG 4K TV", "E4002B"),
    originalPrice: 64990,
    discountedPrice: 46990,
    coupon: "TV28",
    expiry: "2026-08-09",
    popularity: 74,
    dateAdded: "2026-07-19",
  },
  {
    id: "12",
    slug: "ajio-formal-shirt-pack",
    title: "Ajio Men's Formal Shirt (Pack of 2)",
    description: "Wrinkle-resistant cotton-blend formal shirts for the workweek.",
    categorySlug: "fashion",
    storeSlug: "ajio",
    image: img("Formal Shirts", "2A2A72"),
    originalPrice: 2198,
    discountedPrice: 1099,
    coupon: "AJIO50",
    expiry: "2026-08-13",
    popularity: 55,
    dateAdded: "2026-07-14",
  },
  {
    id: "13",
    slug: "firstcry-baby-stroller",
    title: "LuvLap Baby Stroller with Canopy",
    description: "Lightweight, foldable stroller with adjustable canopy and recline seat.",
    categorySlug: "home-kitchen",
    storeSlug: "firstcry",
    image: img("Baby Stroller", "6EC531"),
    originalPrice: 8999,
    discountedPrice: 5399,
    coupon: "BABY40",
    expiry: "2026-08-22",
    popularity: 63,
    dateAdded: "2026-07-16",
  },
  {
    id: "14",
    slug: "tata-cliq-smartwatch",
    title: "Titan Smart Pulse Smartwatch",
    description: "AMOLED display, SpO2 tracking and 7-day battery life.",
    categorySlug: "electronics",
    storeSlug: "tata-cliq",
    image: img("Smart Pulse", "E31E24"),
    originalPrice: 5995,
    discountedPrice: 3597,
    coupon: "TITAN40",
    expiry: "2026-08-17",
    popularity: 70,
    dateAdded: "2026-07-21",
  },
  {
    id: "15",
    slug: "sony-ps5-console",
    title: "Sony PlayStation 5 Slim Console",
    description: "Ultra-fast SSD, ray tracing support and immersive 3D audio.",
    categorySlug: "gaming",
    storeSlug: "amazon",
    image: img("PlayStation 5", "232F3E"),
    originalPrice: 54990,
    discountedPrice: 47990,
    coupon: "PS5DEAL",
    expiry: "2026-08-06",
    popularity: 93,
    dateAdded: "2026-07-28",
    featured: true,
  },
  {
    id: "16",
    slug: "xbox-wireless-controller",
    title: "Xbox Wireless Controller",
    description: "Hybrid D-pad, textured grip and Bluetooth connectivity for PC and console.",
    categorySlug: "gaming",
    storeSlug: "flipkart",
    image: img("Xbox Controller", "2874F0"),
    originalPrice: 5999,
    discountedPrice: 4199,
    coupon: "PLAY30",
    expiry: "2026-08-19",
    popularity: 66,
    dateAdded: "2026-07-17",
  },
  {
    id: "17",
    slug: "netflix-premium-plan",
    title: "Netflix Premium Plan (3 Months)",
    description: "4K Ultra HD streaming on up to 4 screens with downloads for offline viewing.",
    categorySlug: "subscriptions",
    storeSlug: "amazon",
    image: img("Netflix 3M", "232F3E"),
    originalPrice: 1947,
    discountedPrice: 1499,
    expiry: "2026-08-31",
    popularity: 58,
    dateAdded: "2026-07-12",
  },
  {
    id: "18",
    slug: "makemytrip-flight-voucher",
    title: "Flat ₹2,000 Off on Domestic Flights",
    description: "Instant discount voucher valid on domestic flight bookings above ₹5,000.",
    categorySlug: "travel",
    storeSlug: "flipkart",
    image: img("Flight Offer", "2874F0"),
    originalPrice: 5000,
    discountedPrice: 3000,
    coupon: "FLYAWAY",
    expiry: "2026-08-30",
    popularity: 72,
    dateAdded: "2026-07-23",
  },
  {
    id: "19",
    slug: "philips-air-fryer",
    title: "Philips Digital Air Fryer 4.1L",
    description: "Rapid air technology for healthier meals with up to 90% less fat.",
    categorySlug: "home-kitchen",
    storeSlug: "croma",
    image: img("Air Fryer", "00A19C"),
    originalPrice: 10995,
    discountedPrice: 6995,
    coupon: "FRY36",
    expiry: "2026-08-16",
    popularity: 80,
    dateAdded: "2026-07-26",
  },
  {
    id: "20",
    slug: "swiggy-food-voucher",
    title: "Swiggy 50% Off Food Voucher",
    description: "Get 50% off up to ₹150 on your next 3 orders from partner restaurants.",
    categorySlug: "food",
    storeSlug: "amazon",
    image: img("Food Voucher", "232F3E"),
    originalPrice: 450,
    discountedPrice: 225,
    coupon: "EAT50",
    expiry: "2026-08-04",
    popularity: 64,
    dateAdded: "2026-07-13",
  },
  {
    id: "21",
    slug: "iphone-15-128gb",
    title: "Apple iPhone 15 (128GB)",
    description: "A16 Bionic chip, 48MP main camera and USB-C, in five vibrant colours.",
    categorySlug: "mobiles",
    storeSlug: "apple",
    image: img("iPhone 15", "111111"),
    originalPrice: 79900,
    discountedPrice: 65900,
    coupon: "IPHONE14",
    expiry: "2026-08-07",
    popularity: 97,
    dateAdded: "2026-07-29",
    featured: true,
  },
  {
    id: "22",
    slug: "boat-airdopes-141",
    title: "boAt Airdopes 141 TWS Earbuds",
    description: "42 hours of total playback with ENx technology for clear calls.",
    categorySlug: "electronics",
    storeSlug: "boat",
    image: img("Airdopes 141", "E30613"),
    originalPrice: 1999,
    discountedPrice: 999,
    coupon: "AIRDOPE50",
    expiry: "2026-08-21",
    popularity: 71,
    dateAdded: "2026-07-20",
  },
  {
    id: "23",
    slug: "lakme-skincare-combo",
    title: "Lakme Absolute Skincare Combo",
    description: "Cleanser, toner and moisturizer set for daily radiant skin.",
    categorySlug: "beauty",
    storeSlug: "nykaa",
    image: img("Skincare Combo", "FC2779"),
    originalPrice: 1999,
    discountedPrice: 1299,
    coupon: "GLOW35",
    expiry: "2026-08-24",
    popularity: 57,
    dateAdded: "2026-07-11",
  },
  {
    id: "24",
    slug: "asus-rog-strix-laptop",
    title: "Asus ROG Strix G16 Gaming Laptop",
    description: "Intel Core i7, RTX 4060 and a 165Hz display for competitive gaming.",
    categorySlug: "gaming",
    storeSlug: "reliance-digital",
    image: img("ROG Strix G16", "E4002B"),
    originalPrice: 149990,
    discountedPrice: 119990,
    coupon: "ROG20",
    expiry: "2026-08-03",
    popularity: 89,
    dateAdded: "2026-07-27",
  },
];

export function getDealBySlug(slug: string): Deal | undefined {
  return deals.find((d) => d.slug === slug);
}

export function getStoreBySlug(slug: string): Store | undefined {
  return stores.find((s) => s.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function dealsForStore(slug: string): Deal[] {
  return deals.filter((d) => d.storeSlug === slug);
}

export function dealsForCategory(slug: string): Deal[] {
  return deals.filter((d) => d.categorySlug === slug);
}

export function storeDealCount(slug: string): number {
  return deals.filter((d) => d.storeSlug === slug).length;
}

export function categoryDealCount(slug: string): number {
  return deals.filter((d) => d.categorySlug === slug).length;
}
